src/services/ec2/connections.ts
Fixes typo in field for ec2 to elasticBeanstalkEnv connection
=> fix(ec2): fix connection field to elasticBeanstalkEnv

src/services/billing/mutation.ts, src/services/billing/schema.graphql, src/services/flowLogs/mutation.ts, src/services/flowLogs/schema.graphql, src/types/generated.ts
[CG-1631](https://autoclouddev.atlassian.net/browse/CG-1631)
- Fixed mutations files to enable upsert.
=> fix: Fixed some duplication issues without destroying data first

src/services/apiGatewayResource/data.ts, src/services/apiGatewayRestApi/data.ts, src/services/cloud9/data.ts, src/services/cloudFormationStack/data.ts, src/services/cloudfront/data.ts, src/services/cloudwatch/data.ts, src/services/cloudwatchLogs/data.ts, src/services/ebs/data.ts, src/services/ecr/data.ts, src/services/eksCluster/data.ts, src/services/elastiCacheCluster/data.ts, src/services/elastiCacheReplicationGroup/data.ts, src/services/emrCluster/data.ts, src/services/emrInstance/data.ts, src/services/emrStep/data.ts, src/services/iamInstanceProfile/data.ts, src/services/iamUser/data.ts, src/services/iot/data.ts, src/services/lambda/data.ts, src/services/rdsCluster/data.ts, src/services/rdsDbInstance/data.ts, src/services/s3/data.ts, src/services/sns/data.ts, src/services/transitGateway/data.ts, src/services/transitGatewayAttachment/data.ts
=>  fix: fixed services that returned only the first page of paged results

src/services/elb/format.ts, src/services/elb/schema.graphql, src/types/generated.ts
=> fix: Added SSLCertificateId needed for NIST 16.5 rule

src/services/apiGatewayRestApi/data.ts, src/services/cloudfront/data.ts, src/services/elasticBeanstalkApplication/data.ts, src/services/sns/data.ts
=> fix: Added missing return to resolve promise

src/services/s3/format.ts, src/services/s3/schema.graphql, src/types/generated.ts
=> fix: Added ACL Grants needed for aws cis 1.3.0-3.3 rule

src/services/routeTable/format.ts
Fix for route table property `mainRouteTable`
=> fix(services): fix route table service mainRouteTable property

src/services/natGateway/format.ts, src/services/natGateway/schema.graphql, src/types/generated.ts
* Add additional data for Nat Gateway
=> fix(services): fix nat gateway service data

package.json, yarn.lock
=> fix(deps): update sdk dep

src/services/index.ts
=> fix(release): Memory usage fix

src/services/iamRole/data.ts
- Fixed role name exception using optional chaining.
=> fix: Optional chaining for last used details

src/services/iamPolicy/schema.graphql, src/types/generated.ts, src/types/index.ts, src/utils/format.ts
[CG-1258](https://autoclouddev.atlassian.net/browse/CG-1258)
- This adds NotAction, NotPrincipal, and NotResource elements to each IAM policy statement if they exist
=> fix: add missing statement elements needed for the policy definitions

src/services/iamPolicy/schema.graphql, src/services/iamRole/connections.ts, src/services/iamRole/data.ts, src/services/iamRole/format.ts, src/services/iamRole/schema.graphql, src/types/generated.ts
[CG-1262](https://autoclouddev.atlassian.net/browse/CG-1262?atlOrigin=eyJpIjoiMGVlNWFmZWM0MGE0NGE0OGIyYzYzOWEyMTYxMGVjOTAiLCJwIjoiaiJ9)
- Adds the inline policies(name and JSON formatted document)
- Adds permission boundary ARN and relationship to iamPolicy that matches that ARN
=> fix(iamRole): relate iamPermissionsBoundary policy, include inlinePolicies JSON objects

src/services/iamRole/format.ts, src/types/generated.ts
- Replaces the cuid method with the generateUniqueId method from cloudgraph/sdk
=> fix(iamRole): replace inlinePolicies id gen method from cuid to generateUniqueId

src/services/iamRole/data.ts
- Fixes permission boundary bug
- Added null checks
=> fix(iamRole): iamPermissionsBoundary and inlinePolicies bug fixes

package.json, src/services/index.ts, src/types/generated.ts, yarn.lock
CVE vulnerabilities remediations that affect all packages that use this package as a dependency
https://github.com/cloudgraphdev/sdk/pull/30
=> fix: cve vulnerabilities remediations

package.json, src/services/index.ts, yarn.lock
=> feat(creds): update credentials flow to support sso

README.md, src/enums/resources.ts, src/enums/schemasMap.ts, src/enums/serviceAliases.ts, src/enums/serviceMap.ts, src/enums/services.ts, src/properties/logger.ts, src/services/account/schema.graphql, src/services/securityHub/data.ts, src/services/securityHub/format.ts, src/services/securityHub/index.ts, src/services/securityHub/mutation.ts, src/services/securityHub/schema.graphql, src/types/generated.ts
=> feat(CG-1311): add AWS security hub

CHANGELOG.md, README.md, package.json, src/enums/resources.ts, src/enums/schemasMap.ts, src/enums/serviceAliases.ts, src/enums/serviceMap.ts, src/enums/services.ts, src/properties/logger.ts, src/services/account/schema.graphql, src/services/index.ts, src/services/securityHub/data.ts, src/services/securityHub/format.ts, src/services/securityHub/index.ts, src/services/securityHub/mutation.ts, src/services/securityHub/schema.graphql, src/types/generated.ts, yarn.lock
=> Beta release

src/services/index.ts
=> feat(auth): support mfa based auth

src/services/index.ts
Reverts cloudgraphdev/cloudgraph-provider-aws#108
=> Revert "feat(auth): support mfa based auth"

src/services/index.ts
=> fix(auth): add debug log for mfa

src/services/ebsSnapshot/data.ts, src/services/iamRole/data.ts, src/types/generated.ts
=> fix(services): fix iam role data crash

src/services/vpc/data.ts
=> fix(services): whitespace fixs

src/enums/regions.ts
In this PR, we are adding new regions
=> feat: add new regions

src/enums/serviceAliases.ts, src/services/account/schema.graphql, src/services/apiGatewayResource/format.ts, src/services/apiGatewayResource/schema.graphql, src/services/apiGatewayStage/format.ts, src/services/apiGatewayStage/schema.graphql, src/services/msk/connections.ts, src/services/msk/schema.graphql, src/services/route53Record/format.ts, src/services/securityGroup/schema.graphql, src/services/subnet/schema.graphql, src/services/tag/connections.ts, src/types/generated.ts, src/utils/ids.ts
=> feat(aws): Added some adjustment needed for TF

src/services/cloudfront/format.ts, src/services/cloudfront/schema.graphql, src/services/eksCluster/data.ts, src/services/eksCluster/format.ts, src/services/eksCluster/schema.graphql, src/types/generated.ts
=> feat(aws): Update cloudfront and eksCluster

src/services/iamPolicy/schema.graphql, src/services/lambda/data.ts, src/services/lambda/format.ts, src/services/lambda/schema.graphql, src/types/generated.ts, src/utils/format.ts
[EP-3183](https://autoclouddev.atlassian.net/browse/EP-3183)
- Included EventSourceMappings for lambda function.
- Included Layers for lambda function.
- Included statementsIds permissions.
- Included EventInvokeConfig for lambda function.
=> feat: Added more information to lambda service

src/services/iamGroup/format.ts, src/services/iamGroup/schema.graphql, src/services/iamRole/format.ts, src/services/iamRole/schema.graphql, src/services/iamUser/data.ts, src/services/iamUser/format.ts, src/services/iamUser/schema.graphql, src/types/generated.ts
=> feat(aws): support missing iam services

src/enums/relations.ts, src/services/ecsCluster/data.ts, src/services/ecsService/data.ts, src/services/ecsService/format.ts, src/services/ecsService/schema.graphql, src/services/ecsTaskDefinition/data.ts, src/types/generated.ts
=> feat(aws): support missing ecs services

src/services/docdbCluster/data.ts, src/services/eksCluster/data.ts, src/services/elasticBeanstalkApplication/data.ts, src/services/elasticBeanstalkEnvironment/data.ts, src/services/sesDomain/data.ts, src/services/sesEmail/data.ts, src/services/systemsManagerParameter/data.ts, src/services/systemsManagerParameter/format.ts
=> fix(aws): fixes for beta release review

README.md, package.json, src/services/index.ts, src/utils/errorLog.ts, yarn.lock
=> feat: collect provider errors

src/services/ecsTaskDefinition/format.ts
=> fix(ecsTaskDefinition): fix keys of null error

src/services/secretsManager/data.ts
=> fix(secretsManager): get all data pages
